yamlname: Notion to GitHub Pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-node: '20'

      - name: Convert Notion to Markdown
        uses: tailflow/notion-jam@v1
        with:
          notion_secret: ${{ secrets.NOTION_SECRET }}
          notion_database: ${{ secrets.NOTION_DATABASE_ID }}
          output_dir: './docs'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
